# Generated by Django 4.0.3 on 2022-03-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_id', models.CharField(max_length=50, unique=True)),
                ('seq_id', models.CharField(max_length=100, unique=True)),
                ('CRISPR_start', models.PositiveBigIntegerField()),
                ('CRISPR_end', models.PositiveBigIntegerField()),
                ('sea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.sea')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=100, unique=True)),
                ('faa_id', models.CharField(max_length=100, unique=True)),
                ('protein_start', models.PositiveBigIntegerField()),
                ('protein_end', models.PositiveBigIntegerField()),
                ('E_value', models.FloatField()),
                ('distace_between_CRISPR_pro', models.BigIntegerField()),
                ('length', models.PositiveBigIntegerField()),
                ('anno_name', models.CharField(max_length=200)),
                ('pfam_anno_name', models.CharField(max_length=200)),
                ('function', models.CharField(max_length=1000)),
                ('crispr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.sequence')),
            ],
        ),
    ]
