# Generated by Django 4.0.3 on 2022-03-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='faa_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='protein',
            name='protein_id',
            field=models.CharField(max_length=100),
        ),
    ]
